version: '3'

services:
  postgres:
    image: postgres:12
    container_name: コンテナ名
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ユーザ名
      POSTGRES_PASSWORD: パスワード
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: メールアドレス
      PGADMIN_DEFAULT_PASSWORD: パスワード
    ports:
      - 8083:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
